on:
  push:
    branches: [main]
    paths:
      - 'packages/chungking-core/**'
      - '.github/workflows/chungking-core-ci.yml'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'packages/chungking-core/**'
      - '.github/workflows/chungking-core-ci.yml'

name: chungking-core

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.1

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: pnpm

      - run: pnpm install

      - uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: ${{ github.sha }}

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: pnpm

      - run: pnpm --filter "@resir014/chungking-core" run validate
        env:
          CI: true
