on:
  push:
    branches: [trunk]
  pull_request:
    types: [opened, synchronize]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: '.'
          key: ${{ github.sha }}

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn run validate
        env:
          CI: true

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: '.'
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn workspace @resir014/chungking-react run test:coverage
        env:
          CI: true
